version: '3.2'

services:
  nginx:
    build: 
      context: .
      dockerfile: Dockerfile-nginx
    image: nginx/idsr:2.0.0
    ports:
        - "5000:80"
    restart: always
  database:
    image: postgres:10.12
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - idsr-data:/var/lib/postgresql/data
  ussd-1:
    image: node:10.18.1-alpine3.11
    working_dir: /home/app
    command: npm run dev
    restart: always
    volumes:
      - type: bind
        source: ./
        target: /home/app/
    deploy:
      replicas: 1
volumes:
  idsr-data:
    driver: local